version: "2"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile-app
        container_name: cardviewer-app
        ports:
            - "80:80"
        restart: always
        mem_limit: 512m
    db:
        build:
            context: .
            dockerfile: Dockerfile-db
        container_name: cardviewer-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
